<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BondsSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // Seed Issuers
        $issuers = [
            [
                'issuer_short_name' => 'ABMB',
                'issuer_name' => 'Alliance Bank Malaysia Berhad',
                'registration_number' => '198201008390',
                'debenture' => 'Fixed Rate Subordinated Notes',
                'trustee_fee_amount_1' => 50000.00,
                'trustee_fee_amount_2' => 25000.00,
                'trustee_role_1' => 'Bond Trustee',
                'trustee_role_2' => 'Security Trustee',
                'reminder_1' => '2025-02-15',
                'reminder_2' => '2025-03-15',
                'reminder_3' => '2025-04-15',
                'trust_deed_date' => '2023-01-20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'issuer_short_name' => 'CIMB',
                'issuer_name' => 'CIMB Bank Berhad',
                'registration_number' => '197201001799',
                'debenture' => 'Medium Term Notes',
                'trustee_fee_amount_1' => 75000.00,
                'trustee_fee_amount_2' => 40000.00,
                'trustee_role_1' => 'Bond Trustee',
                'trustee_role_2' => 'Security Trustee',
                'reminder_1' => '2025-03-10',
                'reminder_2' => '2025-04-10',
                'reminder_3' => '2025-05-10',
                'trust_deed_date' => '2022-11-05',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'issuer_short_name' => 'MBB',
                'issuer_name' => 'Maybank Berhad',
                'registration_number' => '196001000142',
                'debenture' => 'Sukuk Wakalah',
                'trustee_fee_amount_1' => 60000.00,
                'trustee_fee_amount_2' => 30000.00,
                'trustee_role_1' => 'Sukuk Trustee',
                'trustee_role_2' => 'Security Trustee',
                'reminder_1' => '2025-04-20',
                'reminder_2' => '2025-05-20',
                'reminder_3' => '2025-06-20',
                'trust_deed_date' => '2023-06-15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('issuers')->insert($issuers);

        // Seed Bonds
        $bonds = [
            [
                'bond_sukuk_name' => 'ABMB Subordinated Notes Series 1',
                'sub_name' => 'Series 1',
                'rating' => 'AA3',
                'category' => 'Conventional',
                'principal' => '500000000',
                'isin_code' => 'MYA1000001',
                'stock_code' => 'ABMB01',
                'instrument_code' => 'ABM0125',
                'sub_category' => 'Subordinated Notes',
                'issue_date' => '2020-02-10',
                'maturity_date' => '2030-02-10',
                'coupon_rate' => 4.5000,
                'coupon_type' => 'Fixed',
                'coupon_frequency' => 'Semi-annual',
                'day_count' => 'Actual/365',
                'issue_tenure_years' => 10.0000,
                'residual_tenure_years' => 5.0033,
                'last_traded_yield' => 4.25,
                'last_traded_price' => 101.50,
                'last_traded_amount' => 5000000.00,
                'last_traded_date' => '2025-02-01',
                'coupon_accrual' => '2025-02-01',
                'prev_coupon_payment_date' => '2024-08-10',
                'first_coupon_payment_date' => '2020-08-10',
                'next_coupon_payment_date' => '2025-02-10',
                'last_coupon_payment_date' => '2030-02-10',
                'amount_issued' => 500000000.00,
                'amount_outstanding' => 500000000.00,
                'lead_arranger' => 'Alliance Investment Bank',
                'facility_agent' => 'Alliance Investment Bank',
                'facility_code' => 'ABM-001',
                'status' => 'Active',
                'approval_datetime' => '2020-01-15 10:30:00',
                'issuer_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bond_sukuk_name' => 'CIMB MTN Program 2022',
                'sub_name' => 'Series 2',
                'rating' => 'AAA',
                'category' => 'Conventional',
                'principal' => '750000000',
                'isin_code' => 'MYA1000002',
                'stock_code' => 'CIMB01',
                'instrument_code' => 'CMB0227',
                'sub_category' => 'Medium Term Notes',
                'issue_date' => '2022-11-15',
                'maturity_date' => '2027-11-15',
                'coupon_rate' => 4.2500,
                'coupon_type' => 'Fixed',
                'coupon_frequency' => 'Quarterly',
                'day_count' => 'Actual/365',
                'issue_tenure_years' => 5.0000,
                'residual_tenure_years' => 2.6890,
                'last_traded_yield' => 4.10,
                'last_traded_price' => 102.00,
                'last_traded_amount' => 10000000.00,
                'last_traded_date' => '2025-01-15',
                'coupon_accrual' => '2025-01-15',
                'prev_coupon_payment_date' => '2024-11-15',
                'first_coupon_payment_date' => '2023-02-15',
                'next_coupon_payment_date' => '2025-02-15',
                'last_coupon_payment_date' => '2027-11-15',
                'amount_issued' => 750000000.00,
                'amount_outstanding' => 750000000.00,
                'lead_arranger' => 'CIMB Investment Bank',
                'facility_agent' => 'CIMB Investment Bank',
                'facility_code' => 'CIMB-001',
                'status' => 'Active',
                'approval_datetime' => '2022-10-20 14:15:00',
                'issuer_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bond_sukuk_name' => 'Maybank Sukuk Wakalah 2023',
                'sub_name' => 'Series 1',
                'rating' => 'AAA',
                'category' => 'Islamic',
                'principal' => '1000000000',
                'isin_code' => 'MYA1000003',
                'stock_code' => 'MYBK01',
                'instrument_code' => 'MBB0633',
                'sub_category' => 'Sukuk Wakalah',
                'issue_date' => '2023-06-30',
                'maturity_date' => '2033-06-30',
                'coupon_rate' => 5.0000,
                'coupon_type' => 'Fixed',
                'coupon_frequency' => 'Semi-annual',
                'day_count' => 'Actual/365',
                'issue_tenure_years' => 10.0000,
                'residual_tenure_years' => 8.3890,
                'last_traded_yield' => 4.95,
                'last_traded_price' => 100.50,
                'last_traded_amount' => 15000000.00,
                'last_traded_date' => '2025-01-20',
                'coupon_accrual' => '2025-01-20',
                'prev_coupon_payment_date' => '2024-12-30',
                'first_coupon_payment_date' => '2023-12-30',
                'next_coupon_payment_date' => '2025-06-30',
                'last_coupon_payment_date' => '2033-06-30',
                'amount_issued' => 1000000000.00,
                'amount_outstanding' => 1000000000.00,
                'lead_arranger' => 'Maybank Investment Bank',
                'facility_agent' => 'Maybank Investment Bank',
                'facility_code' => 'MBB-001',
                'status' => 'Active',
                'approval_datetime' => '2023-06-10 09:45:00',
                'issuer_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('bonds')->insert($bonds);

        // Seed Rating Movements
        $ratingMovements = [
            [
                'rating_agency' => 'RAM',
                'effective_date' => '2024-01-15',
                'rating_tenure' => 'Long Term',
                'rating' => 'AA3',
                'rating_action' => 'Affirmed',
                'rating_outlook' => 'Stable',
                'rating_watch' => 'None',
                'bond_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rating_agency' => 'MARC',
                'effective_date' => '2024-02-20',
                'rating_tenure' => 'Long Term',
                'rating' => 'AAA',
                'rating_action' => 'Affirmed',
                'rating_outlook' => 'Stable',
                'rating_watch' => 'None',
                'bond_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rating_agency' => 'RAM',
                'effective_date' => '2024-07-05',
                'rating_tenure' => 'Long Term',
                'rating' => 'AAA',
                'rating_action' => 'Affirmed',
                'rating_outlook' => 'Stable',
                'rating_watch' => 'None',
                'bond_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('rating_movements')->insert($ratingMovements);

        // Seed Payment Schedules
        $paymentSchedules = [
            [
                'start_date' => '2024-08-10',
                'end_date' => '2025-02-09',
                'payment_date' => '2025-02-10',
                'ex_date' => '2025-02-03',
                'coupon_rate' => 4.50,
                'adjustment_date' => null,
                'bond_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_date' => '2025-02-10',
                'end_date' => '2025-08-09',
                'payment_date' => '2025-08-10',
                'ex_date' => '2025-08-03',
                'coupon_rate' => 4.50,
                'adjustment_date' => null,
                'bond_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_date' => '2024-11-15',
                'end_date' => '2025-02-14',
                'payment_date' => '2025-02-15',
                'ex_date' => '2025-02-08',
                'coupon_rate' => 4.25,
                'adjustment_date' => null,
                'bond_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_date' => '2025-02-15',
                'end_date' => '2025-05-14',
                'payment_date' => '2025-05-15',
                'ex_date' => '2025-05-08',
                'coupon_rate' => 4.25,
                'adjustment_date' => null,
                'bond_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_date' => '2024-12-30',
                'end_date' => '2025-06-29',
                'payment_date' => '2025-06-30',
                'ex_date' => '2025-06-23',
                'coupon_rate' => 5.00,
                'adjustment_date' => null,
                'bond_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_date' => '2025-06-30',
                'end_date' => '2025-12-29',
                'payment_date' => '2025-12-30',
                'ex_date' => '2025-12-23',
                'coupon_rate' => 5.00,
                'adjustment_date' => null,
                'bond_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('payment_schedules')->insert($paymentSchedules);

        // Seed Redemptions
        $redemptions = [
            [
                'last_call_date' => '2030-01-10',
                'allow_partial_call' => true,
                'redeem_nearest_denomination' => true,
                'bond_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_call_date' => '2027-10-15',
                'allow_partial_call' => false,
                'redeem_nearest_denomination' => true,
                'bond_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'last_call_date' => '2033-05-30',
                'allow_partial_call' => true,
                'redeem_nearest_denomination' => true,
                'bond_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('redemptions')->insert($redemptions);

        // Seed Call Schedules
        $callSchedules = [
            [
                'start_date' => '2025-02-10',
                'end_date' => '2026-02-09',
                'call_price' => 102.00,
                'redemption_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_date' => '2026-02-10',
                'end_date' => '2027-02-09',
                'call_price' => 101.50,
                'redemption_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_date' => '2025-11-15',
                'end_date' => '2026-11-14',
                'call_price' => 101.00,
                'redemption_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_date' => '2025-06-30',
                'end_date' => '2028-06-29',
                'call_price' => 103.00,
                'redemption_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_date' => '2028-06-30',
                'end_date' => '2031-06-29',
                'call_price' => 101.50,
                'redemption_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('call_schedules')->insert($callSchedules);

        // Seed Lockout Periods
        $lockoutPeriods = [
            [
                'start_date' => '2020-02-10',
                'end_date' => '2025-02-09',
                'redemption_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_date' => '2022-11-15',
                'end_date' => '2025-11-14',
                'redemption_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_date' => '2023-06-30',
                'end_date' => '2025-06-29',
                'redemption_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('lockout_periods')->insert($lockoutPeriods);

        // Seed Trading Activities
        $tradingActivities = [
            [
                'trade_date' => '2025-01-15',
                'input_time' => '10:30:00',
                'amount' => 5000000.00,
                'price' => 101.50,
                'yield' => 4.25,
                'value_date' => '2025-01-17',
                'bond_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'trade_date' => '2025-01-20',
                'input_time' => '11:45:00',
                'amount' => 10000000.00,
                'price' => 102.00,
                'yield' => 4.10,
                'value_date' => '2025-01-22',
                'bond_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'trade_date' => '2025-01-25',
                'input_time' => '14:15:00',
                'amount' => 15000000.00,
                'price' => 100.50,
                'yield' => 4.95,
                'value_date' => '2025-01-27',
                'bond_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('trading_activities')->insert($tradingActivities);

        // Seed Announcements
        $announcements = [
            [
                'announcement_date' => '2025-01-10',
                'category' => 'Corporate',
                'sub_category' => 'Financial Results',
                'title' => 'Alliance Bank Quarterly Results',
                'description' => 'Alliance Bank Malaysia Berhad announces Q4 2024 financial results',
                'content' => 'Alliance Bank Malaysia Berhad today announced its financial results for the fourth quarter of 2024, reporting a net profit of RM500 million.',
                'attachment' => 'abmb_q4_2024.pdf',
                'source' => 'Bursa Malaysia',
                'issuer_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'announcement_date' => '2025-01-15',
                'category' => 'Corporate',
                'sub_category' => 'Dividend',
                'title' => 'CIMB Final Dividend Announcement',
                'description' => 'CIMB Bank Berhad announces final dividend for financial year 2024',
                'content' => 'CIMB Bank Berhad is pleased to announce a final dividend of 25 sen per share for the financial year ending 31 December 2024.',
                'attachment' => 'cimb_dividend_2024.pdf',
                'source' => 'Bursa Malaysia',
                'issuer_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'announcement_date' => '2025-01-20',
                'category' => 'Corporate',
                'sub_category' => 'Corporate Exercise',
                'title' => 'Maybank Sukuk Extension',
                'description' => 'Maybank Berhad announces extension of Sukuk Wakalah program',
                'content' => 'Maybank Berhad is pleased to announce the extension of its Sukuk Wakalah program by an additional RM5 billion, bringing the total program size to RM20 billion.',
                'attachment' => 'maybank_sukuk_extension.pdf',
                'source' => 'Bursa Malaysia',
                'issuer_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('announcements')->insert($announcements);

        // Seed Facility Informations
        $facilityInformations = [
            [
                'facility_code' => 'ABM-001',
                'facility_number' => 'ABMB/2020/001',
                'facility_name' => 'Alliance Bank Subordinated Notes Program',
                'principle_type' => 'Conventional',
                'islamic_concept' => null,
                'maturity_date' => '2030-02-10',
                'instrument' => 'Subordinated Notes',
                'instrument_type' => 'Tier 2 Capital',
                'guaranteed' => false,
                'total_guaranteed' => null,
                'indicator' => 'Financial Institution',
                'facility_rating' => 'AA3',
                'facility_amount' => 1000000000.00,
                'available_limit' => 500000000.00,
                'outstanding_amount' => 500000000.00,
                'trustee_security_agent' => 'AmanahRaya Trustees Berhad',
                'lead_arranger' => 'Alliance Investment Bank',
                'facility_agent' => 'Alliance Investment Bank',
                'availability_date' => '2025-02-10',
                'issuer_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_code' => 'CIMB-001',
                'facility_number' => 'CIMB/2022/001',
                'facility_name' => 'CIMB Medium Term Notes Program',
                'principle_type' => 'Conventional',
                'islamic_concept' => null,
                'maturity_date' => '2027-11-15',
                'instrument' => 'Medium Term Notes',
                'instrument_type' => 'Senior Unsecured',
                'guaranteed' => false,
                'total_guaranteed' => null,
                'indicator' => 'Financial Institution',
                'facility_rating' => 'AAA',
                'facility_amount' => 5000000000.00,
                'available_limit' => 4250000000.00,
                'outstanding_amount' => 750000000.00,
                'trustee_security_agent' => 'AmanahRaya Trustees Berhad',
                'lead_arranger' => 'CIMB Investment Bank',
                'facility_agent' => 'CIMB Investment Bank',
                'availability_date' => '2030-11-15',
                'issuer_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'facility_code' => 'MBB-001',
                'facility_number' => 'MBB/2023/001',
                'facility_name' => 'Maybank Sukuk Wakalah Program',
                'principle_type' => 'Islamic',
                'islamic_concept' => 'Wakalah',
                'maturity_date' => '2033-06-30',
                'instrument' => 'Sukuk',
                'instrument_type' => 'Senior Unsecured',
                'guaranteed' => false,
                'total_guaranteed' => null,
                'indicator' => 'Financial Institution',
                'facility_rating' => 'AAA',
                'facility_amount' => 10000000000.00,
                'available_limit' => 9000000000.00,
                'outstanding_amount' => 1000000000.00,
                'trustee_security_agent' => 'AmanahRaya Trustees Berhad',
                'lead_arranger' => 'Maybank Investment Bank',
                'facility_agent' => 'Maybank Investment Bank',
                'availability_date' => '2035-06-30',
                'issuer_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('facility_informations')->insert($facilityInformations);

        // Seed Related Documents
        $relatedDocuments = [
            [
                'document_name' => 'Trust Deed',
                'document_type' => 'Trust Deed',
                'upload_date' => '2020-01-20',
                'file_path' => 'documents/abmb/trust_deed.pdf',
                'facility_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document_name' => 'Information Memorandum',
                'document_type' => 'Information Memorandum',
                'upload_date' => '2020-01-25',
                'file_path' => 'documents/abmb/im.pdf',
                'facility_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document_name' => 'Trust Deed',
                'document_type' => 'Trust Deed',
                'upload_date' => '2022-11-05',
                'file_path' => 'documents/cimb/trust_deed.pdf',
                'facility_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document_name' => 'Information Memorandum',
                'document_type' => 'Information Memorandum',
                'upload_date' => '2022-11-10',
                'file_path' => 'documents/cimb/im.pdf',
                'facility_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document_name' => 'Trust Deed',
                'document_type' => 'Trust Deed',
                'upload_date' => '2023-06-15',
                'file_path' => 'documents/mbb/trust_deed.pdf',
                'facility_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'document_name' => 'Information Memorandum',
                'document_type' => 'Information Memorandum',
                'upload_date' => '2023-06-20',
                'file_path' => 'documents/mbb/im.pdf',
                'facility_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('related_documents')->insert($relatedDocuments);

        // Seed Charts
        $charts = [
            [
                'availability_date' => '2025-02-01',
                'approval_date_time' => '2025-01-31 15:30:00',
                'chart_type' => 'Price History',
                'chart_data' => json_encode([
                    ['date' => '2024-08-01', 'price' => 100.25],
                    ['date' => '2024-09-01', 'price' => 100.50],
                    ['date' => '2024-10-01', 'price' => 100.75],
                    ['date' => '2024-11-01', 'price' => 101.00],
                    ['date' => '2024-12-01', 'price' => 101.25],
                    ['date' => '2025-01-01', 'price' => 101.50],
                ]),
                'period_from' => '2024-08-01',
                'period_to' => '2025-01-31',
                'bond_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'availability_date' => '2025-02-01',
                'approval_date_time' => '2025-01-31 16:15:00',
                'chart_type' => 'Price History',
                'chart_data' => json_encode([
                    ['date' => '2024-08-01', 'price' => 99.75],
                    ['date' => '2024-09-01', 'price' => 99.90],
                    ['date' => '2024-10-01', 'price' => 100.00],
                    ['date' => '2024-11-01', 'price' => 100.25],
                    ['date' => '2024-12-01', 'price' => 100.40],
                    ['date' => '2025-01-01', 'price' => 100.50],
                ]),
                'period_from' => '2024-08-01',
                'period_to' => '2025-01-31',
                'bond_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('charts')->insert($charts);

        // Seed Trustee Fees
        $trusteeFees = [
            [
                'month' => 'Jan',
                'date' => 15,
                'issuer' => 'ABMB',
                'description' => 'Annual Trustee Fee for Subordinated Notes',
                'fees_rm' => 50000.00,
                'start_anniversary_date' => '2024-01-20',
                'end_anniversary_date' => '2025-01-19',
                'memo_to_fad' => '2025-01-05',
                'invoice_no' => 'INV-ABMB-2025-001',
                'date_letter_to_issuer' => '2025-01-10',
                'first_reminder' => '2025-02-10',
                'second_reminder' => '2025-03-10',
                'third_reminder' => null,
                'payment_received' => '2025-02-01',
                'tt_cheque_no' => 'TT-1234567',
                'memo_receipt_to_fad' => '2025-02-05',
                'receipt_to_issuer' => '2025-02-10',
                'receipt_no' => 'RCPT-ABMB-2025-001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'month' => 'Feb',
                'date' => 5,
                'issuer' => 'CIMB',
                'description' => 'Annual Trustee Fee for Medium Term Notes',
                'fees_rm' => 75000.00,
                'start_anniversary_date' => '2024-11-05',
                'end_anniversary_date' => '2025-11-04',
                'memo_to_fad' => '2025-01-20',
                'invoice_no' => 'INV-CIMB-2025-001',
                'date_letter_to_issuer' => '2025-01-25',
                'first_reminder' => null,
                'second_reminder' => null,
                'third_reminder' => null,
                'payment_received' => '2025-02-15',
                'tt_cheque_no' => 'TT-2345678',
                'memo_receipt_to_fad' => '2025-02-20',
                'receipt_to_issuer' => '2025-02-25',
                'receipt_no' => 'RCPT-CIMB-2025-001',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'month' => 'Jun',
                'date' => 15,
                'issuer' => 'MBB',
                'description' => 'Annual Trustee Fee for Sukuk Wakalah',
                'fees_rm' => 60000.00,
                'start_anniversary_date' => '2024-06-15',
                'end_anniversary_date' => '2025-06-14',
                'memo_to_fad' => '2025-06-01',
                'invoice_no' => 'INV-MBB-2025-001',
                'date_letter_to_issuer' => '2025-06-05',
                'first_reminder' => null,
                'second_reminder' => null,
                'third_reminder' => null,
                'payment_received' => null,
                'tt_cheque_no' => null,
                'memo_receipt_to_fad' => null,
                'receipt_to_issuer' => null,
                'receipt_no' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('trustee_fees')->insert($trusteeFees);

        // Seed Compliance Covenants
        $complianceCovenants = [
            [
                'issuer_short_name' => 'ABMB',
                'financial_year_end' => '2024-12-31',
                'audited_financial_statements' => 'Received',
                'unaudited_financial_statements' => 'Received',
                'compliance_certificate' => 'Received',
                'finance_service_cover_ratio' => '1.5',
                'annual_budget' => 'Received',
                'computation_of_finance_to_ebitda' => 'Received',
                'ratio_information_on_use_of_proceeds' => 'Received',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'issuer_short_name' => 'CIMB',
                'financial_year_end' => '2024-12-31',
                'audited_financial_statements' => 'Received',
                'unaudited_financial_statements' => 'Received',
                'compliance_certificate' => 'Received',
                'finance_service_cover_ratio' => '1.7',
                'annual_budget' => 'Received',
                'computation_of_finance_to_ebitda' => 'Received',
                'ratio_information_on_use_of_proceeds' => 'Received',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'issuer_short_name' => 'MBB',
                'financial_year_end' => '2024-12-31',
                'audited_financial_statements' => 'Received',
                'unaudited_financial_statements' => 'Received',
                'compliance_certificate' => 'Received',
                'finance_service_cover_ratio' => '1.8',
                'annual_budget' => 'Received',
                'computation_of_finance_to_ebitda' => 'Received',
                'ratio_information_on_use_of_proceeds' => 'Received',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('compliance_covenants')->insert($complianceCovenants);
    }
}