<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DefaultUsersSeeder extends Seeder
{
    public function run()
    {
        $users = [
            // Admin Users
            [
                'name' => 'MOHD ASHRAF BIN AZMI',
                'email' => 'ashraf_azmi@artrustees.com.my',
                'role' => 'admin',
                'permission' => 'DCMTRD',
                'job_title' => 'ASISSTANT MANAGER',
                'department' => 'DIGITALIZATION DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'MUQRI AMIN BIN MOHD SHAMSUDDIN',
                'email' => 'muqri.amin@artrustees.com.my',
                'role' => 'admin',
                'permission' => 'DCMTRD',
                'job_title' => 'SENIOR EXECUTIVE',
                'department' => 'DIGITALIZATION DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'NUR FARZANA BINTI ZAIRUL AZMI',
                'email' => 'nurfarzana@artrustees.com.my',
                'role' => 'admin',
                'permission' => 'DCMTRD',
                'job_title' => 'EXECUTIVE',
                'department' => 'DIGITALIZATION DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],

            // DCMT Users
            [
                'name' => 'ROSLIM SYAH BIN IDRIS',
                'email' => 'roslimsyah@artrustees.com.my',
                'role' => 'user',
                'permission' => '[DCMTRD, REITS]',
                'job_title' => 'SENIOR MANAGER',
                'department' => 'DEBT CAPITAL MARKET & TRUST UNIT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'MOHAMAD AZAHARI BIN AB AZIZ',
                'email' => 'mohamad.azahari@artrustees.com.my',
                'role' => 'user',
                'job_title' => 'ASSISTANT MANAGER',
                'department' => 'DEBT CAPITAL MARKET & TRUST UNIT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => 'DCMTRD',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'FARAEDALISMALINA BINTI ZAKARIA',
                'email' => 'faraedalismalina@artrustees.com.my',
                'role' => 'user',
                'job_title' => 'SENIOR EXECUTIVE',
                'department' => 'DEBT CAPITAL MARKET & TRUST UNIT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => 'DCMTRD',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'NOR IZZAH BINTI MOHAMAD ARIFF',
                'email' => 'izzahariff@artrustees.com.my',
                'role' => 'user',
                'job_title' => 'SENIOR EXECUTIVE',
                'department' => 'DEBT CAPITAL MARKET & TRUST UNIT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => 'DCMTRD',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'NUR SAKIENAH BINTI KHAIRUDDIN',
                'email' => 'nursakienah@artrustees.com.my',
                'role' => 'user',
                'job_title' => 'EXECUTIVE',
                'department' => 'DEBT CAPITAL MARKET & TRUST UNIT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => 'DCMTRD',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'MUHAMMAD SAYYIDI BIN MOHD BASIL',
                'email' => 'sayyidi@artrustees.com.my',
                'role' => 'user',
                'job_title' => 'EXECUTIVE',
                'department' => 'DEBT CAPITAL MARKET & TRUST UNIT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => 'DCMTRD',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],

            // REITS Users
            [
                'name' => 'DANG FATHIHAH BINTI IBRAHIM',
                'email' => 'fathihah@artrustees.com.my',
                'role' => 'user',
                'job_title' => 'ASSISTANT MANAGER',
                'department' => 'REAL ESTATE INVESTMENT TRUST UNIT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => 'REITS',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'NURUL SHAHIDAH BINTI RAS TAMAJIS',
                'email' => 'nurul.shahidah@artrustees.com.my',
                'role' => 'user',
                'job_title' => 'SENIOR EXECUTIVE',
                'department' => 'REAL ESTATE INVESTMENT TRUST UNIT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => 'REITS',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'MUHAMMAD AFIS BIN AZMAN',
                'email' => 'afis.azman@artrustees.com.my',
                'role' => 'user',
                'job_title' => 'EXECUTIVE',
                'department' => 'REAL ESTATE INVESTMENT TRUST UNIT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => 'REITS',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],

            // Compliance
            [
                'name' => 'RASIDHA BINTI SAKHUDIN @ SALLEHUDIN',
                'email' => 'rasidha@artrustees.com.my',
                'role' => 'compliance',
                'job_title' => 'SENIOR MANAGER',
                'department' => 'COMPLIANCE MONITORING DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => '[DCMTRD, REITS]',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'DALILA BINTI ZOBIR',
                'email' => 'dalila@artrustees.com.my',
                'role' => 'compliance',
                'job_title' => 'MANAGER',
                'department' => 'COMPLIANCE MONITORING DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => '[DCMTRD, REITS]',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'SHARIFAH NURAINI BINTI SYED KHALID',
                'email' => 'nuraini@artrustees.com.my',
                'role' => 'compliance',
                'job_title' => 'MANAGER',
                'department' => 'COMPLIANCE MONITORING DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => '[DCMTRD, REITS]',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'DIAN NADIRAH BINTI JASRI',
                'email' => 'dianjasri@artrustees.com.my',
                'role' => 'compliance',
                'job_title' => 'ASSISTANT MANAGER',
                'department' => 'COMPLIANCE MONITORING DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => '[DCMTRD, REITS]',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'NUR EFFA NAJIHAH BINTI ABDUL WAHAB',
                'email' => 'effanajihah@artrustees.com.my',
                'role' => 'compliance',
                'job_title' => 'SENIOR EXECUTIVE',
                'department' => 'COMPLIANCE MONITORING DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => '[DCMTRD, REITS]',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'KHAIRUN NISA BINTI ABD RAZAK',
                'email' => 'khairunnisa_razak@artrustees.com.my',
                'role' => 'compliance',
                'job_title' => 'EXECUTIVE',
                'department' => 'COMPLIANCE MONITORING DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => '[DCMTRD, REITS]',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'NURUL SYAFIQAH BINTI ABD KADIR',
                'email' => 'nurul.syafiqah@artrustees.com.my',
                'role' => 'compliance',
                'job_title' => 'EXECUTIVE',
                'department' => 'COMPLIANCE MONITORING DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => '[DCMTRD, REITS]',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],

            // Legal
            [
                'name' => 'ZULHIDA BINTI ABD MAURAD',
                'email' => 'zulhida@artrustees.com.my',
                'role' => 'legal',
                'job_title' => 'SENIOR MANAGER',
                'department' => 'LEGAL DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => '[DCMTRD, REITS]',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'NUR FARAH BINTI MOHD KAMAL',
                'email' => 'nur.farah@artrustees.com.my',
                'role' => 'legal',
                'job_title' => 'ASSISTANT MANAGER',
                'department' => 'LEGAL DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => '[DCMTRD, REITS]',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'ASMA NUR QURAISYAH BINTI YUNUS',
                'email' => 'asma.quraisyah@artrustees.com.my',
                'role' => 'legal',
                'job_title' => 'SENIOR EXECUTIVE',
                'department' => 'LEGAL DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => '[DCMTRD, REITS]',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'AMIR AMSYAR BIN MOHD NAZIR',
                'email' => 'amir.amsyar@artrustees.com.my',
                'role' => 'legal',
                'job_title' => 'SENIOR EXECUTIVE',
                'department' => 'LEGAL DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => '[DCMTRD, REITS]',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'MAISARAH HUMAIRA BINTI MEOR YAHAYA',
                'email' => 'maisarah.humaira@artrustees.com.my',
                'role' => 'legal',
                'job_title' => 'EXECUTIVE',
                'department' => 'LEGAL DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => '[DCMTRD, REITS]',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
            [
                'name' => 'KHARIESHA BINTI KHALID',
                'email' => 'khariesha@artrustees.com.my',
                'role' => 'legal',
                'job_title' => 'EXECUTIVE',
                'department' => 'LEGAL DEPARTMENT',
                'office_location' => 'AMANAHRAYA TRUSTEES BERHAD',
                'permission' => '[DCMTRD, REITS]',
                'email_verified_at' => now(),
                'password' => bcrypt('Dcmtrd@2025'),
                'two_factor_code' => null,
                'two_factor_expires_at' => null,
                'two_factor_verified' => false,
                'two_factor_enabled' => false,
                'remember_token' => null,
            ],
        ];

        foreach ($users as $user) {
            User::create($user);
        }
    }
}
