<?php

namespace Database\Seeders;

use Carbon\Carbon;
use App\Models\Lease;
use App\Models\Tenant;
use Illuminate\Database\Seeder;

class LeaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $leases = [
            [
                'tenant_name' => 'JOHOR CORPORATION',
                'lease_name' => 'JOHOR CORPORATION',
                'demised_premises' => 'Suite 1, Level 6',
                'permitted_use' => 'Gymnasium',
                'rental_amount' => 5000.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2021-05-01',
                'end_date' => '2024-05-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Al Bagus Food and Beverage Sdn Bhd',
                'lease_name' => 'Al Bagus Lease',
                'demised_premises' => 'Lot No. 202b, Second Floor',
                'permitted_use' => 'Operation of a Fast Food Restaurant under the trade name of Marrybrown only.',
                'rental_amount' => 7000.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'BNX Delight Sdn Bhd',
                'lease_name' => 'BNX Delight Lease',
                'demised_premises' => 'Lot No. 212-213, Second Floor',
                'permitted_use' => 'Operation of a pork-free Japanese Restaurant under the trade name of KINSAHI only.',
                'rental_amount' => 0.00, // Update with actual rental amount if available
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'BNX Takahara Sdn Bhd',
                'lease_name' => 'BNX Takahara Lease',
                'demised_premises' => 'Lot No. 215-216, Second Floor',
                'permitted_use' => 'Operation of a non-halal Japanese shabu-shabu restaurant under the trade name of ARASHI SHABU-SHABU only.',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Caring Pharmacy Retail Management Sdn Bhd',
                'lease_name' => 'Caring Pharmacy Lease',
                'demised_premises' => 'Lot No. 218, Second Floor',
                'permitted_use' => 'Pharmacy and retailing of health care products under the trade name of Caring Pharmacy only.',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Chamelon Sdn Bhd',
                'lease_name' => 'Chamelon Lease',
                'demised_premises' => 'Lot No. 131, First Floor',
                'permitted_use' => 'Fashion accessories including earrings, brooches, pendants, tiaras, bracelets, and hair bands under the trade name of Chamelon.',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Chrisna Jenio Sdn Bhd',
                'lease_name' => 'Chrisna Jenio Lease',
                'demised_premises' => 'Lot No. 235, Second Floor',
                'permitted_use' => 'Retailing of pretzels under the trade name of Auntie Anne\'s only.',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Era Sag (JB) Sdn Bhd',
                'lease_name' => 'Era Sag Lease',
                'demised_premises' => 'Lot No. SK01, Second Floor',
                'permitted_use' => 'Retail sale of nuts, dates, dried fruits, chocolates, candies, oud perfume, foods, drinks, and gift hampers under the trade name of SAUDAGAR KURMA only.',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Eyeflex Optometrix Sdn Bhd',
                'lease_name' => 'Eyeflex Optometrix Lease',
                'demised_premises' => 'Lot No. 102, First Floor',
                'permitted_use' => 'Operation as an optician and retailing of optometry products under the trade name of EYECON only.',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'F.O.S Apparel Group Sdn Bhd',
                'lease_name' => 'F.O.S Apparel Group Lease',
                'demised_premises' => 'Lot No. 227, 228, 229 & 230, Second Floor',
                'permitted_use' => 'Retail sale of ladies, men and children apparels and other related accessories under the trade name of F.O.S only.',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Grand Companies Sdn Bhd',
                'lease_name' => 'Grand Companies Lease',
                'demised_premises' => 'Lot No. 203, Second Floor',
                'permitted_use' => "The retail operations of a TONY ROMA'S restaurant concept only.",
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'KPK Quantity Surveyors (Semenanjung) Sdn Bhd',
                'lease_name' => 'KPK Quantity Surveyors Lease',
                'demised_premises' => 'Suite 3, Level 23',
                'permitted_use' => 'Office',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Johor Corporation',
                'lease_name' => 'Johor Corporation Lease',
                'demised_premises' => 'Suite 1, Level 13, 24 & 25',
                'permitted_use' => 'Office',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Habib Jewels Franchise Sdn Bhd',
                'lease_name' => 'Habib Jewels Franchise Lease',
                'demised_premises' => 'KG-3, Ground Floor',
                'permitted_use' => "The retail sale of Jewelry under the trade name of 'PANDORA' only.",
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'JPS Fashions (Malaysia) Sdn Bhd',
                'lease_name' => 'JPS Fashions Lease',
                'demised_premises' => 'Lot No. 137, First Floor',
                'permitted_use' => 'Jelly Bunny',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'La Mior Sdn Bhd',
                'lease_name' => 'La Mior Lease',
                'demised_premises' => 'Lot 222, Second Floor',
                'permitted_use' => 'Nail spa under the trade name of La Mior Nail Spa Only.',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'LAC Global Brands (Malaysia) Sdn Bhd',
                'lease_name' => 'LAC Global Brands Lease',
                'demised_premises' => 'Lot No. 217B, Second Floor',
                'permitted_use' => 'Retailing of vitamins, supplements, minerals, herbs, sport nutrition, diet and energy and health and beauty product under the trade name of LAC Nutrition for Life only.',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Azmi & Associates',
                'lease_name' => 'Azmi & Associates Lease',
                'demised_premises' => 'Suite 1A, Level 20',
                'permitted_use' => 'Advocates & Solicitors',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Maxenta Cosmeceuticals Sdn Bhd',
                'lease_name' => 'Maxenta Lease',
                'demised_premises' => 'Lot No. 223, Second Floor',
                'permitted_use' => 'Retailing of a facial salon and laser centre under the trade name of MX Laser only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2023-01-01',
                'end_date' => '2026-01-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'TT Dotcom Sdn Bhd',
                'lease_name' => 'TT Dotcom Lease',
                'demised_premises' => 'Suite 1, Ground Floor',
                'permitted_use' => 'Business of Data Telecommunication only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-06-01',
                'end_date' => '2027-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Howden Insurance Brokers Sdn Bhd',
                'lease_name' => 'Howden Insurance Lease',
                'demised_premises' => 'Suite 2, Level 6',
                'permitted_use' => 'Office Use',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 4,
                'start_date' => '2021-05-01',
                'end_date' => '2025-05-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Cemara Astka Solutions Sdn Bhd',
                'lease_name' => 'Cemara Lease',
                'demised_premises' => 'Suite 1B, Level 15',
                'permitted_use' => 'The business of Management Service only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2023-03-01',
                'end_date' => '2026-03-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Johor Corporation',
                'lease_name' => 'Johor Corp Lease',
                'demised_premises' => 'Suite 1, Level 22',
                'permitted_use' => 'Office',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2020-10-01',
                'end_date' => '2025-10-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Mynews Retails Sdn Bhd',
                'lease_name' => 'Mynews Lease',
                'demised_premises' => 'KG-1A, Ground Floor',
                'permitted_use' => 'Retail sale of newspaper & magazines, cigarettes and beverages under the trade name of MYNEWS only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2021-12-01',
                'end_date' => '2024-12-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Nails Studio JBCC',
                'lease_name' => 'Nails Studio Lease',
                'demised_premises' => 'Lot No. SK02, Second Floor',
                'permitted_use' => 'Operation of nail spa with retailing of OPI under the trade name of Nails Studio only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2022-08-01',
                'end_date' => '2025-08-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'NDIS Group Development',
                'lease_name' => 'NDIS Lease',
                'demised_premises' => 'SK10, Second Floor',
                'permitted_use' => 'The operation of a bakery, pastry, cake & beverage under the trade name of Mr Roti Coffee only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 4,
                'start_date' => '2023-01-01',
                'end_date' => '2027-01-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Orax Enterprise',
                'lease_name' => 'Orax Lease',
                'demised_premises' => 'Lot No. SK11, Second Floor',
                'permitted_use' => 'Retail sale of traditional batik under the trade name of RYA SOPHIA COUTURE only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2022-06-01',
                'end_date' => '2025-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Struys Leslie Oswin',
                'lease_name' => 'Struys Lease',
                'demised_premises' => 'Suite 2, Level 23',
                'permitted_use' => 'Office Only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2021-05-01',
                'end_date' => '2024-05-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Padini Dot Com Sdn Bhd',
                'lease_name' => 'Padini Lease',
                'demised_premises' => '138 & 139, First Floor',
                'permitted_use' => 'The retail sale of ladies, men & children’s apparels, shoes, gifts, stationery, and other related accessories under the Padini Concept Store only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2020-12-01',
                'end_date' => '2025-12-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Richeese Factory Malaysia Sdn Bhd',
                'lease_name' => 'Richeese Lease',
                'demised_premises' => 'Lot No. 202c, Second Floor',
                'permitted_use' => 'Food & Beverages operation of a fast food restaurant concept under the trade name of RICHEESE FACTORY only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2023-02-01',
                'end_date' => '2026-02-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'SEKVS Trading Sdn Bhd',
                'lease_name' => 'SEKVS Lease',
                'demised_premises' => 'G08 & G09, Ground Floor',
                'permitted_use' => 'Food & Beverages operation of a western restaurant concept under the trade name of DELIRIUM CAFFEINATORS BY ANTIPODEAN only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2023-06-01',
                'end_date' => '2026-06-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Willis (Malaysia) Sdn Bhd',
                'lease_name' => 'Willis Lease',
                'demised_premises' => 'Suite 1B, Level 20',
                'permitted_use' => 'Office Use',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2022-04-01',
                'end_date' => '2027-04-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Luggage Lockers PLT',
                'lease_name' => 'Luggage Lockers Lease',
                'demised_premises' => 'Lot No. KG06, CPL4-01, Ground Floor & Car Park Fourth Floor',
                'permitted_use' => 'Operation of the locker under the trade name of LUGGAGELOCKERS.MY',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2021-07-01',
                'end_date' => '2024-07-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Sorella (M) Sdn Bhd',
                'lease_name' => 'Sorella Lease',
                'demised_premises' => '130, First Floor',
                'permitted_use' => 'The retail sale of Lingerie, bra, panty, girdle, sleepwear, sportswear under the name of OUTLET only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2022-09-01',
                'end_date' => '2025-09-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Tea Garden Restaurant (MY) Sdn Bhd',
                'lease_name' => 'Tea Garden Lease',
                'demised_premises' => '233, Second Floor',
                'permitted_use' => 'Food & Beverages operation of a western restaurant concept under the trade name of TEA GARDEN only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 4,
                'start_date' => '2023-03-01',
                'end_date' => '2027-03-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'TEC Malaysia Sdn Bhd',
                'lease_name' => 'TEC Lease',
                'demised_premises' => '202A, Second Floor',
                'permitted_use' => 'Pork-free Thai restaurant under the trade name of Thai Express only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2021-08-01',
                'end_date' => '2024-08-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Azman, Wong, Salleh & Co',
                'lease_name' => 'Azman Wong Lease',
                'demised_premises' => 'Suite 2&3, Level 20',
                'permitted_use' => 'Chartered Accountants only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 5,
                'start_date' => '2020-10-01',
                'end_date' => '2025-10-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'JL Project Sdn Bhd',
                'lease_name' => 'JL Project Lease',
                'demised_premises' => 'Suite 2, Level 8',
                'permitted_use' => 'Office',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2023-01-01',
                'end_date' => '2026-01-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Mohd Akhir & Partners',
                'lease_name' => 'Mohd Akhir Lease',
                'demised_premises' => 'Suite 1, Level 18',
                'permitted_use' => 'Advocates & Solicitors',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 4,
                'start_date' => '2022-05-01',
                'end_date' => '2026-05-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Thai Odyssey Group Sdn Bhd',
                'lease_name' => 'Thai Odyssey Lease',
                'demised_premises' => '221C, Second Floor',
                'permitted_use' => 'The operation of a massage and Spa Centre under the name of THAI ODYSSEY only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2023-07-01',
                'end_date' => '2026-07-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'The Coffee Bean & Tea Leaf (M) Sdn Bhd',
                'lease_name' => 'Coffee Bean Lease',
                'demised_premises' => 'G01, Ground Floor',
                'permitted_use' => 'Operational of The Coffee Bean & Tea Leaf café concept only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2023-01-01',
                'end_date' => '2026-01-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'TMT Delight Sdn Bhd',
                'lease_name' => 'TMT Delight Lease',
                'demised_premises' => 'G05 - G07, Ground Floor',
                'permitted_use' => 'Western, pastry and bakery restaurant concept under the trade name of MANZANITA PATISSERIE & BOULANGERIE only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2023-01-01',
                'end_date' => '2026-01-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Vincci Ladies’ Specialties Centre Sdn Bhd',
                'lease_name' => 'Vincci Lease',
                'demised_premises' => '135, First Floor',
                'permitted_use' => 'The retail sale of women’s footwear and related accessories under the name of VINCCI only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2023-01-01',
                'end_date' => '2026-01-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Vitality Boost Sdn Bhd',
                'lease_name' => 'Vitality Boost Lease',
                'demised_premises' => 'Lot No. K2-2, Second Floor',
                'permitted_use' => 'Operation of a juice bar under the trade name of Boost Juice only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2023-01-01',
                'end_date' => '2026-01-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Vivo Food Sdn Bhd',
                'lease_name' => 'Vivo Lease',
                'demised_premises' => 'Lot No. 202, Second Floor',
                'permitted_use' => 'Food & Beverages operation of a western restaurant concept under the trade name of Vivo Pizza only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2023-01-01',
                'end_date' => '2026-01-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Yee Fong Hung (M) Sdn Bhd',
                'lease_name' => 'Yee Fong Hung Lease',
                'demised_premises' => '101, First Floor',
                'permitted_use' => 'The retail sale of ladies, men, and children’s apparels under the trade name of BRANDS OUTLET only',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2023-01-01',
                'end_date' => '2026-01-01',
                'status' => 'Draft',
            ],
            [
                'tenant_name' => 'Yung Fa Retail Sdn Bhd',
                'lease_name' => 'Yung Fa Lease',
                'demised_premises' => '138 & 139, First Floor',
                'permitted_use' => 'The retail sale of ladies, men & children’s apparels, shoes, gifts, stationery and other related accessories under the trade name of YFS CONCEPT STORE',
                'rental_amount' => 0.00,
                'rental_frequency' => 'monthly',
                'option_to_renew' => true,
                'term_years' => 3,
                'start_date' => '2023-01-01',
                'end_date' => '2026-01-01',
                'status' => 'Draft',
            ]

        ];

        foreach ($leases as $data) {
            $tenant = Tenant::where('name', $data['tenant_name'])->first();

            if ($tenant) {
                Lease::create([
                    'tenant_id' => $tenant->id,
                    'lease_name' => $data['lease_name'],
                    'demised_premises' => $data['demised_premises'],
                    'permitted_use' => $data['permitted_use'],
                    'rental_amount' => $data['rental_amount'],
                    'rental_frequency' => $data['rental_frequency'],
                    'option_to_renew' => $data['option_to_renew'],
                    'term_years' => $data['term_years'],
                    'start_date' => Carbon::parse($data['start_date']),
                    'end_date' => Carbon::parse($data['end_date']),
                    'status' => $data['status'],
                ]);
            }
        }
    }
}