<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

// Models
use App\Models\Property;
use App\Models\Portfolio;

class PropertySeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // Seed Properties
        $properties = [
            // Portfolio ID 1 (Al Aqar)
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-001',
                'name' => 'KUANTAN WELLNESS CENTRE',
                'address' => '123 Wellness Avenue',
                'city' => 'Kuantan',
                'state' => 'Pahang',
                'country' => 'Malaysia',
                'postal_code' => '25000',
                'land_size' => 3000.00,
                'gross_floor_area' => 18000.00,
                'usage' => 'Healthcare',
                'value' => 20000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 20000000.00,
                'market_value' => 22000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Modern wellness facility'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-002',
                'name' => 'KPJ KAJANG SPECIALIST HOSPITAL',
                'address' => '456 Medical Drive',
                'city' => 'Kajang',
                'state' => 'Selangor',
                'country' => 'Malaysia',
                'postal_code' => '43000',
                'land_size' => 5000.00,
                'gross_floor_area' => 25000.00,
                'usage' => 'Healthcare',
                'value' => 35000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 35000000.00,
                'market_value' => 38000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Specialist hospital facility'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-003',
                'name' => 'KPJ SELANGOR SPECIALIST HOSPITAL',
                'address' => '789 Healthcare Boulevard',
                'city' => 'Shah Alam',
                'state' => 'Selangor',
                'country' => 'Malaysia',
                'postal_code' => '40000',
                'land_size' => 6000.00,
                'gross_floor_area' => 30000.00,
                'usage' => 'Healthcare',
                'value' => 40000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 40000000.00,
                'market_value' => 43000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Comprehensive specialist hospital'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-004',
                'name' => 'KPJ PERDANA SPECIALIST HOSPITAL',
                'address' => '101 Medical Center Road',
                'city' => 'Kota Bharu',
                'state' => 'Kelantan',
                'country' => 'Malaysia',
                'postal_code' => '15000',
                'land_size' => 4500.00,
                'gross_floor_area' => 20000.00,
                'usage' => 'Healthcare',
                'value' => 30000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 30000000.00,
                'market_value' => 32000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Specialized medical facility'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-005',
                'name' => 'DAMAI WELLNESS CENTRE',
                'address' => '250 Damai Street',
                'city' => 'Kuala Lumpur',
                'state' => 'Federal Territory',
                'country' => 'Malaysia',
                'postal_code' => '50400',
                'land_size' => 2800.00,
                'gross_floor_area' => 15000.00,
                'usage' => 'Healthcare',
                'value' => 25000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 25000000.00,
                'market_value' => 27000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Wellness and rehabilitation center'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-006',
                'name' => 'KPJ PENANG SPECIALIST HOSPITAL',
                'address' => '570 Medical Complex',
                'city' => 'Georgetown',
                'state' => 'Penang',
                'country' => 'Malaysia',
                'postal_code' => '10450',
                'land_size' => 5500.00,
                'gross_floor_area' => 28000.00,
                'usage' => 'Healthcare',
                'value' => 38000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 38000000.00,
                'market_value' => 42000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Advanced specialty hospital'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-007',
                'name' => 'KPJ DAMANSARA SPECIALIST HOSPITAL',
                'address' => '119 Damansara Heights',
                'city' => 'Petaling Jaya',
                'state' => 'Selangor',
                'country' => 'Malaysia',
                'postal_code' => '50490',
                'land_size' => 7000.00,
                'gross_floor_area' => 35000.00,
                'usage' => 'Healthcare',
                'value' => 45000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 45000000.00,
                'market_value' => 48000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Premium specialist hospital'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-008',
                'name' => 'KPJ AMPANG PUTERI SPECIALIST HOSPITAL',
                'address' => '1 Jalan Ampang',
                'city' => 'Ampang',
                'state' => 'Selangor',
                'country' => 'Malaysia',
                'postal_code' => '68000',
                'land_size' => 6500.00,
                'gross_floor_area' => 32000.00,
                'usage' => 'Healthcare',
                'value' => 42000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 42000000.00,
                'market_value' => 45000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Comprehensive medical center'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-009',
                'name' => 'KPJ PUTERI SPECIALIST HOSPITAL',
                'address' => '33 Jalan Puteri',
                'city' => 'Johor Bahru',
                'state' => 'Johor',
                'country' => 'Malaysia',
                'postal_code' => '80100',
                'land_size' => 5200.00,
                'gross_floor_area' => 26000.00,
                'usage' => 'Healthcare',
                'value' => 36000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 36000000.00,
                'market_value' => 39000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Modern healthcare facility'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-010',
                'name' => 'KPJ IPOH SPECIALIST HOSPITAL',
                'address' => '26 Jalan Raja',
                'city' => 'Ipoh',
                'state' => 'Perak',
                'country' => 'Malaysia',
                'postal_code' => '30450',
                'land_size' => 5800.00,
                'gross_floor_area' => 29000.00,
                'usage' => 'Healthcare',
                'value' => 38000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 38000000.00,
                'market_value' => 41000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Full-service specialist hospital'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-011',
                'name' => 'KPJ KLANG SPECIALIST HOSPITAL',
                'address' => '300 Jalan Klang',
                'city' => 'Klang',
                'state' => 'Selangor',
                'country' => 'Malaysia',
                'postal_code' => '41200',
                'land_size' => 5000.00,
                'gross_floor_area' => 25000.00,
                'usage' => 'Healthcare',
                'value' => 34000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 34000000.00,
                'market_value' => 37000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Specialist medical facility'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-012',
                'name' => 'KPJ JOHOR SPECIALIST HOSPITAL',
                'address' => '39 Jalan Tebrau',
                'city' => 'Johor Bahru',
                'state' => 'Johor',
                'country' => 'Malaysia',
                'postal_code' => '80100',
                'land_size' => 6200.00,
                'gross_floor_area' => 31000.00,
                'usage' => 'Healthcare',
                'value' => 40000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 40000000.00,
                'market_value' => 43000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Advanced medical center'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Education',
                'batch_no' => 'AQ-013',
                'name' => 'KPJ INTERNATIONAL COLLEGE BUKIT MERTAJAM',
                'address' => '100 College Road',
                'city' => 'Bukit Mertajam',
                'state' => 'Penang',
                'country' => 'Malaysia',
                'postal_code' => '14000',
                'land_size' => 12000.00,
                'gross_floor_area' => 40000.00,
                'usage' => 'Education',
                'value' => 50000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 50000000.00,
                'market_value' => 53000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Medical education facility'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-014',
                'name' => 'TAIPING MEDICAL CENTRE',
                'address' => '5 Medical Park',
                'city' => 'Taiping',
                'state' => 'Perak',
                'country' => 'Malaysia',
                'postal_code' => '34000',
                'land_size' => 4000.00,
                'gross_floor_area' => 18000.00,
                'usage' => 'Healthcare',
                'value' => 28000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 28000000.00,
                'market_value' => 30000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Regional medical center'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Education',
                'batch_no' => 'AQ-015',
                'name' => 'KPJH INTERNATIONAL COLLEGE NILAI',
                'address' => '25 Education Park',
                'city' => 'Nilai',
                'state' => 'Negeri Sembilan',
                'country' => 'Malaysia',
                'postal_code' => '71800',
                'land_size' => 15000.00,
                'gross_floor_area' => 45000.00,
                'usage' => 'Education',
                'value' => 55000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 55000000.00,
                'market_value' => 58000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Healthcare education campus'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-016',
                'name' => 'PROJECT OTTO',
                'address' => '88 Development Zone',
                'city' => 'Kuala Lumpur',
                'state' => 'Federal Territory',
                'country' => 'Malaysia',
                'postal_code' => '50250',
                'land_size' => 8000.00,
                'gross_floor_area' => 35000.00,
                'usage' => 'Healthcare',
                'value' => 60000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 60000000.00,
                'market_value' => 65000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'New healthcare development project'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-017',
                'name' => 'KEDAH MEDICAL CENTRE',
                'address' => '15 Medical Avenue',
                'city' => 'Alor Setar',
                'state' => 'Kedah',
                'country' => 'Malaysia',
                'postal_code' => '05100',
                'land_size' => 5500.00,
                'gross_floor_area' => 27000.00,
                'usage' => 'Healthcare',
                'value' => 32000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 32000000.00,
                'market_value' => 34000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Regional medical facility'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-018',
                'name' => 'KPJ PASIR GUDANG SH',
                'address' => '55 Jalan Industri',
                'city' => 'Pasir Gudang',
                'state' => 'Johor',
                'country' => 'Malaysia',
                'postal_code' => '81700',
                'land_size' => 4800.00,
                'gross_floor_area' => 22000.00,
                'usage' => 'Healthcare',
                'value' => 30000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 30000000.00,
                'market_value' => 32000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Specialist hospital facility'
            ],
            [
                'portfolio_id' => 1,
                'category' => 'Healthcare',
                'batch_no' => 'AQ-019',
                'name' => 'KPJ Tawakkal Sh & KPJ Damansara SH',
                'address' => '9 Tawakkal Street',
                'city' => 'Kuala Lumpur',
                'state' => 'Federal Territory',
                'country' => 'Malaysia',
                'postal_code' => '50300',
                'land_size' => 12500.00,
                'gross_floor_area' => 60000.00,
                'usage' => 'Healthcare',
                'value' => 85000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 85000000.00,
                'market_value' => 90000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Combined specialist hospital facilities'
            ],
            
            // Portfolio ID 2 (Al Salam)
            [
                'portfolio_id' => 2,
                'category' => 'Food & Beverage',
                'batch_no' => 'AS-001',
                'name' => 'KFC AYER HITAM',
                'address' => '123 Ayer Hitam Street',
                'city' => 'Ayer Hitam',
                'state' => 'Johor',
                'country' => 'Malaysia',
                'postal_code' => '86100',
                'land_size' => 800.00,
                'gross_floor_area' => 1200.00,
                'usage' => 'Commercial',
                'value' => 3000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 3000000.00,
                'market_value' => 3200000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Fast food restaurant'
            ],
            [
                'portfolio_id' => 2,
                'category' => 'Retail',
                'batch_no' => 'AS-002',
                'name' => 'KOMTAR JBCC',
                'address' => '80 Jalan Wong Ah Fook',
                'city' => 'Johor Bahru',
                'state' => 'Johor',
                'country' => 'Malaysia',
                'postal_code' => '80000',
                'land_size' => 15000.00,
                'gross_floor_area' => 75000.00,
                'usage' => 'Commercial',
                'value' => 150000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 150000000.00,
                'market_value' => 165000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Shopping mall and commercial complex'
            ],
            [
                'portfolio_id' => 2,
                'category' => 'Food & Beverage',
                'batch_no' => 'AS-003',
                'name' => 'QSR PROPERTIES',
                'address' => '500 QSR Avenue',
                'city' => 'Kuala Lumpur',
                'state' => 'Federal Territory',
                'country' => 'Malaysia',
                'postal_code' => '50400',
                'land_size' => 5000.00,
                'gross_floor_area' => 15000.00,
                'usage' => 'Commercial',
                'value' => 25000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 25000000.00,
                'market_value' => 28000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Quick service restaurant properties'
            ],
            [
                'portfolio_id' => 2,
                'category' => 'Retail',
                'batch_no' => 'AS-004',
                'name' => 'MART KEMPAS',
                'address' => '25 Jalan Kempas',
                'city' => 'Johor Bahru',
                'state' => 'Johor',
                'country' => 'Malaysia',
                'postal_code' => '81200',
                'land_size' => 10000.00,
                'gross_floor_area' => 35000.00,
                'usage' => 'Commercial',
                'value' => 40000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 40000000.00,
                'market_value' => 42000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Shopping mart and retail complex'
            ],
            [
                'portfolio_id' => 2,
                'category' => 'Industrial',
                'batch_no' => 'AS-005',
                'name' => 'CENTRE WAREHOUSE',
                'address' => '100 Industrial Zone',
                'city' => 'Shah Alam',
                'state' => 'Selangor',
                'country' => 'Malaysia',
                'postal_code' => '40100',
                'land_size' => 15000.00,
                'gross_floor_area' => 25000.00,
                'usage' => 'Industrial',
                'value' => 22000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 22000000.00,
                'market_value' => 24000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Central distribution warehouse'
            ],
            [
                'portfolio_id' => 2,
                'category' => 'Food & Beverage',
                'batch_no' => 'AS-006',
                'name' => 'KFC DT WANGSA MAJU',
                'address' => '45 Wangsa Maju Boulevard',
                'city' => 'Kuala Lumpur',
                'state' => 'Federal Territory',
                'country' => 'Malaysia',
                'postal_code' => '53300',
                'land_size' => 1000.00,
                'gross_floor_area' => 1500.00,
                'usage' => 'Commercial',
                'value' => 4500000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 4500000.00,
                'market_value' => 4800000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Fast food restaurant with drive-through'
            ],
            [
                'portfolio_id' => 2,
                'category' => 'Office',
                'batch_no' => 'AS-007',
                'name' => 'CTOS DATA SYSTEMS SDN BHD',
                'address' => '200 Technology Park',
                'city' => 'Petaling Jaya',
                'state' => 'Selangor',
                'country' => 'Malaysia',
                'postal_code' => '46000',
                'land_size' => 5000.00,
                'gross_floor_area' => 20000.00,
                'usage' => 'Office',
                'value' => 35000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 35000000.00,
                'market_value' => 37000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Office building for data systems company'
            ],
            [
                'portfolio_id' => 2,
                'category' => 'Education',
                'batch_no' => 'AS-008',
                'name' => 'KPJ INTERNATIONAL COLLEGE (MCMH)',
                'address' => '75 Education Drive',
                'city' => 'Johor Bahru',
                'state' => 'Johor',
                'country' => 'Malaysia',
                'postal_code' => '80200',
                'land_size' => 12000.00,
                'gross_floor_area' => 35000.00,
                'usage' => 'Education',
                'value' => 45000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 45000000.00,
                'market_value' => 47000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Medical college campus'
            ],
            [
                'portfolio_id' => 2,
                'category' => 'Food & Beverage',
                'batch_no' => 'AS-009',
                'name' => 'PHD ULU TIRAM',
                'address' => '18 Ulu Tiram Street',
                'city' => 'Ulu Tiram',
                'state' => 'Johor',
                'country' => 'Malaysia',
                'postal_code' => '81800',
                'land_size' => 900.00,
                'gross_floor_area' => 1300.00,
                'usage' => 'Commercial',
                'value' => 2800000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 2800000.00,
                'market_value' => 3000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Pizza restaurant outlet'
            ],
            [
                'portfolio_id' => 2,
                'category' => 'Mixed Use',
                'batch_no' => 'AS-010',
                'name' => 'KOMTAR JBCC & MCHM',
                'address' => '85 Jalan Wong Ah Fook',
                'city' => 'Johor Bahru',
                'state' => 'Johor',
                'country' => 'Malaysia',
                'postal_code' => '80000',
                'land_size' => 20000.00,
                'gross_floor_area' => 100000.00,
                'usage' => 'Mixed',
                'value' => 180000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 180000000.00,
                'market_value' => 195000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Shopping mall and medical center complex'
            ],
            
            // Portfolio ID 3 (AMANAH HARTA TANAH PNB (AHP))
            [
                'portfolio_id' => 3,
                'category' => 'Commercial',
                'batch_no' => 'AHP-001',
                'name' => 'CX1, CYBERJAYA',
                'address' => '1 Tech Boulevard',
                'city' => 'Cyberjaya',
                'state' => 'Selangor',
                'country' => 'Malaysia',
                'postal_code' => '63000',
                'land_size' => 10000.00,
                'gross_floor_area' => 45000.00,
                'usage' => 'Office',
                'value' => 80000000.00,
                'ownership' => 'Freehold',
                'share_amount' => 80000000.00,
                'market_value' => 85000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Premium office building'
            ],
            [
                'portfolio_id' => 3,
                'category' => 'Retail',
                'batch_no' => 'AHP-002',
                'name' => 'MYDIN HYPERMARKET, SEREMBAN 2',
                'address' => '25 Seremban 2 Avenue',
                'city' => 'Seremban',
                'state' => 'Negeri Sembilan',
                'country' => 'Malaysia',
                'postal_code' => '70300',
                'land_size' => 25000.00,
                'gross_floor_area' => 60000.00,
                'usage' => 'Retail',
                'value' => 90000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 90000000.00,
                'market_value' => 95000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Large hypermarket complex'
            ],
            
            // Portfolio ID 4 (AMANAH HARTANAH BUMIPUTERA (AHB))
            [
                'portfolio_id' => 4,
                'category' => 'Government',
                'batch_no' => 'AHB-001',
                'name' => 'PENTADBIR TANAH JOHOR BAHRU',
                'address' => '10 Land Office Road',
                'city' => 'Johor Bahru',
                'state' => 'Johor',
                'country' => 'Malaysia',
                'postal_code' => '80000',
                'land_size' => 2500.00,
                'gross_floor_area' => 8000.00,
                'usage' => 'Government Office',
                'value' => 15000000.00,
                'ownership' => 'Leasehold',
                'share_amount' => 15000000.00,
                'market_value' => 16000000.00,
                'prepared_by' => 'System Admin',
                'verified_by' => 'System Verifier',
                'remarks' => 'Land administration office'
            ],
        ];

      // Database insertion code
      foreach ($properties as $property) {
        DB::table('properties')->insert([
            'portfolio_id' => $property['portfolio_id'],
            'category' => $property['category'],
            'batch_no' => $property['batch_no'],
            'name' => $property['name'],
            'address' => $property['address'],
            'city' => $property['city'],
            'state' => $property['state'],
            'country' => $property['country'],
            'postal_code' => $property['postal_code'],
            'land_size' => $property['land_size'],
            'gross_floor_area' => $property['gross_floor_area'],
            'usage' => $property['usage'],
            'value' => $property['value'],
            'ownership' => $property['ownership'],
            'share_amount' => $property['share_amount'],
            'market_value' => $property['market_value'],
            'status' => 'active',
            'prepared_by' => $property['prepared_by'],
            'verified_by' => $property['verified_by'],
            'remarks' => $property['remarks'],
            'created_at' => now(),
            'updated_at' => now()
        ]);
    }
    }
}